In [ ]:
import requests
import pandas as pd
url = "https://raw.githubusercontent.com/TranBang875/seminar2project/main/dataset/train.csv"
response = requests.get(url)

with open("train.csv", "wb") as f:
    f.write(response.content)

df = pd.read_csv("train.csv")
display(df.head())

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,6315ba0d20ed87c6,Or maybe after Ward's been driven off it's my ...,0,0,0,0,0,0
1,e96b768aeaaa2a86,which I omitted foreshadowed the discussion ab...,0,0,0,0,0,0
2,0fb782c63da5262d,At the bottom there was only 1 paragraph from ...,0,0,0,0,0,0
3,3a9656dae4b54ef5,You LOVE Anime!? There are some ANIMES out the...,1,0,0,0,1,0
4,765e185c703c8a72,Do you seriously not realise that there's a di...,0,0,0,0,0,0

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    # 3. Convert the input text to lowercase.
    text = text.lower()
    # 4. Remove non-alphanumeric characters from the text using regular expressions.
    text = re.sub(r'[^a-z0-9\s]', '', text)
    # 5. Remove stop words from the text.
    text = ' '.join([word for word in text.split() if word not in stop_words])
    # 6. Lemmatize the remaining words in the text.
    text = ' '.join([lemmatizer.lemmatize(word) for word in text.split()])
    # 7. Apply the emotion cleaning logic to the text (placeholder for now)
    # This step requires specific logic based on how emotions are represented.
    # For this subtask, we'll assume no specific emotion cleaning is needed beyond general text cleaning.
    return text

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
df['cleaned_comment_text'] = df['comment_text'].apply(clean_text)
display(df[['comment_text', 'cleaned_comment_text']].head())

,comment_text,cleaned_comment_text
0,Or maybe after Ward's been driven off it's my ...,maybe ward driven turn
1,which I omitted foreshadowed the discussion ab...,omitted foreshadowed discussion cold war next ...
2,At the bottom there was only 1 paragraph from ...,bottom 1 paragraph entire poemsong dont believ...
3,You LOVE Anime!? There are some ANIMES out the...,love anime anime suck idiot6884225186
4,Do you seriously not realise that there's a di...,seriously realise there difference free conten...

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
import nltk
from nltk.tokenize import word_tokenize

try:
    df['tokenized_comment_text'] = df['cleaned_comment_text'].apply(word_tokenize)
except LookupError:
    nltk.download('punkt_tab')
    df['tokenized_comment_text'] = df['cleaned_comment_text'].apply(word_tokenize)

display(df[['cleaned_comment_text', 'tokenized_comment_text']].head())

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

,cleaned_comment_text,tokenized_comment_text
0,maybe ward driven turn,"[maybe, ward, driven, turn]"
1,omitted foreshadowed discussion cold war next ...,"[omitted, foreshadowed, discussion, cold, war,..."
2,bottom 1 paragraph entire poemsong dont believ...,"[bottom, 1, paragraph, entire, poemsong, dont,..."
3,love anime anime suck idiot6884225186,"[love, anime, anime, suck, idiot6884225186]"
4,seriously realise there difference free conten...,"[seriously, realise, there, difference, free, ..."

In [ ]:
display(df[['comment_text', 'cleaned_comment_text', 'tokenized_comment_text']].head())

,comment_text,cleaned_comment_text,tokenized_comment_text
0,Or maybe after Ward's been driven off it's my ...,maybe ward driven turn,"[maybe, ward, driven, turn]"
1,which I omitted foreshadowed the discussion ab...,omitted foreshadowed discussion cold war next ...,"[omitted, foreshadowed, discussion, cold, war,..."
2,At the bottom there was only 1 paragraph from ...,bottom 1 paragraph entire poemsong dont believ...,"[bottom, 1, paragraph, entire, poemsong, dont,..."
3,You LOVE Anime!? There are some ANIMES out the...,love anime anime suck idiot6884225186,"[love, anime, anime, suck, idiot6884225186]"
4,Do you seriously not realise that there's a di...,seriously realise there difference free conten...,"[seriously, realise, there, difference, free, ..."

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Join the tokens back into strings for TF-IDF
df['tokenized_comment_text_str'] = df['tokenized_comment_text'].apply(lambda x: ' '.join(x))

tfidf_vectorizer = TfidfVectorizer(max_features=5000) # You can adjust max_features
tfidf_features = tfidf_vectorizer.fit_transform(df['tokenized_comment_text_str'])

print("Shape of TF-IDF features:", tfidf_features.shape)

Shape of TF-IDF features: (143613, 5000)

In [ ]:
import requests

url = "https://raw.githubusercontent.com/TranBang875/seminar2project/main/dataset/test.csv"
response = requests.get(url)

with open("test.csv", "wb") as f:
    f.write(response.content)

test_df = pd.read_csv("test.csv")
display(test_df.head())

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,e2348af2e5759ec2,"Thank you for adding your perspective, I think...",0,0,0,0,0,0
1,233fc6cf45e001b2,"""\n\n A barnstar for you! \n\n The Original B...",0,0,0,0,0,0
2,14b0cd797c10b638,"""\n declares WikiWar on you! \n \nSpread th...",0,0,0,0,0,0
3,b1dcd00e57902a06,Subsidized housing article \nHello.,0,0,0,0,0,0
4,964e9d20812690c5,"""\nDid you even read the source you provided? ...",0,0,0,0,0,0

In [ ]:
test_df['cleaned_comment_text'] = test_df['comment_text'].apply(clean_text)
test_df['tokenized_comment_text'] = test_df['cleaned_comment_text'].apply(word_tokenize)
display(test_df[['comment_text', 'cleaned_comment_text', 'tokenized_comment_text']].head())

,comment_text,cleaned_comment_text,tokenized_comment_text
0,"Thank you for adding your perspective, I think...",thank adding perspective think understand poin...,"[thank, adding, perspective, think, understand..."
1,"""\n\n A barnstar for you! \n\n The Original B...",barnstar original barnstar thanks expansion ta...,"[barnstar, original, barnstar, thanks, expansi..."
2,"""\n declares WikiWar on you! \n \nSpread th...",declares wikiwar spread war adding others talk...,"[declares, wikiwar, spread, war, adding, other..."
3,Subsidized housing article \nHello.,subsidized housing article hello,"[subsidized, housing, article, hello]"
4,"""\nDid you even read the source you provided? ...",even read source provided first section specif...,"[even, read, source, provided, first, section,..."

In [ ]:
test_df['cleaned_comment_text'] = test_df['comment_text'].apply(clean_text)
test_df['tokenized_comment_text'] = test_df['cleaned_comment_text'].apply(word_tokenize)
display(test_df[['comment_text', 'cleaned_comment_text', 'tokenized_comment_text']].head())

,comment_text,cleaned_comment_text,tokenized_comment_text
0,"Thank you for adding your perspective, I think...",thank adding perspective think understand poin...,"[thank, adding, perspective, think, understand..."
1,"""\n\n A barnstar for you! \n\n The Original B...",barnstar original barnstar thanks expansion ta...,"[barnstar, original, barnstar, thanks, expansi..."
2,"""\n declares WikiWar on you! \n \nSpread th...",declares wikiwar spread war adding others talk...,"[declares, wikiwar, spread, war, adding, other..."
3,Subsidized housing article \nHello.,subsidized housing article hello,"[subsidized, housing, article, hello]"
4,"""\nDid you even read the source you provided? ...",even read source provided first section specif...,"[even, read, source, provided, first, section,..."

In [ ]:
test_df['tokenized_comment_text_str'] = test_df['tokenized_comment_text'].apply(lambda x: ' '.join(x))
tfidf_test_features = tfidf_vectorizer.transform(test_df['tokenized_comment_text_str'])

print("Shape of TF-IDF test features:", tfidf_test_features.shape)

Shape of TF-IDF test features: (15958, 5000)

In [ ]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression

# Define the target labels
LABELS = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

x_train = tfidf_features
y_train = df[LABELS]

# Initialize and train the multi-output logistic regression model
model = MultiOutputClassifier(LogisticRegression(max_iter=1000, n_jobs=-1))
model.fit(x_train, y_train)

x_test = tfidf_test_features
y_test = test_df[LABELS]
print("Model training complete.")

Model training complete.

In [ ]:
from sklearn.metrics import f1_score, classification_report

# Make predictions on the test set
y_pred = model.predict(x_test)

# Calculate the F1 score for each label
f1_scores = f1_score(y_test, y_pred, average=None)

# Print the F1 scores for each label
for i, label in enumerate(LABELS):
    print(f"F1 score for {label}: {f1_scores[i]:.4f}")

# Calculate the average F1 score
average_f1_score = f1_score(y_test, y_pred, average='weighted')
print(f"\nAverage F1 score (weighted): {average_f1_score:.4f}")

# Print classification report for precision, recall, and support
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=LABELS))

F1 score for toxic: 0.7309
F1 score for severe_toxic: 0.3319
F1 score for obscene: 0.7313
F1 score for threat: 0.1887
F1 score for insult: 0.6517
F1 score for identity_hate: 0.4024

Average F1 score (weighted): 0.6766

Classification Report:
               precision    recall  f1-score   support

        toxic       0.90      0.61      0.73      1501
 severe_toxic       0.45      0.26      0.33       149
      obscene       0.86      0.63      0.73       809
       threat       0.83      0.11      0.19        47
       insult       0.80      0.55      0.65       769
identity_hate       0.72      0.28      0.40       118

    micro avg       0.85      0.57      0.68      3393
    macro avg       0.76      0.41      0.51      3393
 weighted avg       0.84      0.57      0.68      3393
  samples avg       0.05      0.05      0.05      3393

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.svm import SVC

# Define the target labels
LABELS = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

x_train = tfidf_features
y_train = df[LABELS]

# Initialize and train the multi-output logistic regression model
model = MultiOutputClassifier(SVC())
model.fit(x_train, y_train)

x_test = tfidf_test_features
y_test = test_df[LABELS]
print("Model training complete.")

Model training complete.

In [ ]:
from sklearn.metrics import f1_score, classification_report

# Make predictions on the test set
y_pred = model.predict(x_test)

# Calculate the F1 score for each label
f1_scores = f1_score(y_test, y_pred, average=None)

# Print the F1 scores for each label
for i, label in enumerate(LABELS):
    print(f"F1 score for {label}: {f1_scores[i]:.4f}")

# Calculate the average F1 score
average_f1_score = f1_score(y_test, y_pred, average='weighted')
print(f"\nAverage F1 score (weighted): {average_f1_score:.4f}")

# Print classification report for precision, recall, and support
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=LABELS))

F1 score for toxic: 0.7382
F1 score for severe_toxic: 0.1364
F1 score for obscene: 0.7552
F1 score for threat: 0.1509
F1 score for insult: 0.6667
F1 score for identity_hate: 0.3791

Average F1 score (weighted): 0.6790

Classification Report:
               precision    recall  f1-score   support

        toxic       0.90      0.63      0.74      1501
 severe_toxic       0.44      0.08      0.14       149
      obscene       0.86      0.67      0.76       809
       threat       0.67      0.09      0.15        47
       insult       0.80      0.57      0.67       769
identity_hate       0.83      0.25      0.38       118

    micro avg       0.86      0.58      0.69      3393
    macro avg       0.75      0.38      0.47      3393
 weighted avg       0.84      0.58      0.68      3393
  samples avg       0.05      0.05      0.05      3393

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Naive Bayes

In [ ]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.naive_bayes import MultinomialNB

# Define the target labels
LABELS = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

x_train = tfidf_features
y_train = df[LABELS]

# Initialize and train the multi-output logistic regression model
model = MultiOutputClassifier(MultinomialNB())
model.fit(x_train, y_train)

x_test = tfidf_test_features
y_test = test_df[LABELS]
print("Model training complete.")

Model training complete.

In [ ]:
from sklearn.metrics import f1_score, classification_report, accuracy_score

# Make predictions on the test set
y_pred = model.predict(x_test)

# Calculate the F1 score for each label
f1_scores = f1_score(y_test, y_pred, average=None)

# Print the F1 scores for each label
for i, label in enumerate(LABELS):
    print(f"F1 score for {label}: {f1_scores[i]:.4f}")

# Calculate the average F1 score
average_f1_score = f1_score(y_test, y_pred, average='weighted')
print(f"\nAverage F1 score (weighted): {average_f1_score:.4f}")

# Calculate and print the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy score: {accuracy:.4f}")

# Print classification report for precision, recall, and support
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=LABELS))

F1 score for toxic: 0.6621
F1 score for severe_toxic: 0.2727
F1 score for obscene: 0.6839
F1 score for threat: 0.0000
F1 score for insult: 0.5807
F1 score for identity_hate: 0.2222

Average F1 score (weighted): 0.6073

Accuracy score: 0.9162

Classification Report:
               precision    recall  f1-score   support

        toxic       0.92      0.52      0.66      1501
 severe_toxic       0.55      0.18      0.27       149
      obscene       0.89      0.56      0.68       809
       threat       0.00      0.00      0.00        47
       insult       0.81      0.45      0.58       769
identity_hate       0.88      0.13      0.22       118

    micro avg       0.87      0.48      0.62      3393
    macro avg       0.67      0.31      0.40      3393
 weighted avg       0.86      0.48      0.61      3393
  samples avg       0.05      0.04      0.04      3393

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
from sklearn.metrics import precision_score, recall_score

# Calculate macro and micro average precision, recall, and f1-score
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')

micro_precision = precision_score(y_test, y_pred, average='micro')
micro_recall = recall_score(y_test, y_pred, average='micro')
micro_f1 = f1_score(y_test, y_pred, average='micro')

print(f"\nMacro Average Precision: {macro_precision:.4f}")
print(f"Macro Average Recall: {macro_recall:.4f}")
print(f"Macro Average F1-score: {macro_f1:.4f}")

print(f"\nMicro Average Precision: {micro_precision:.4f}")
print(f"Micro Average Recall: {micro_recall:.4f}")
print(f"Micro Average F1-score: {micro_f1:.4f}")

Macro Average Precision: 0.6742
Macro Average Recall: 0.3060
Macro Average F1-score: 0.4036

Micro Average Precision: 0.8737
Micro Average Recall: 0.4769
Micro Average F1-score: 0.6170

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))